Fixes
Mannaa-Baddour/Sorting-Tuples-in-Go pull request #1
Opened 2022-10-05 23:58 UTC by Mannaa-Baddour

in this pull request, the main issues were addressed.
1) a new separate branch called "fixes" was created to maintain the stability of the master branch.
2) the project has been restructured in a form of packages/modules (please note there was some problems with that which took most of the time, then instead of creating a github repo for the package, it was referred to locally).
3) the conditions of the solution were taken into consideration while creating a better solution using the package "sorting.go"

to be noted:
1- as mentioned earlier creating a module as a repo on github and associate it with the program was taken into consideration but was not able to be met.
2- there are no sufficient data regarding file permissions within the os.OpenFile() function, specifically with os.FileMode(), so os.Create() was used instead.
3- as of defining a tuple type, creating it as a struct was taken into consideration in order to specify 3 and only 3 elements within a tuple, but the indexing would be very much different to handle, so instead a method was associated to the type with a condition of 3 elements tops, even though it's considered a breach for it is derived from a slice.

2022-10-06 06:43 UTC, radwandeeb requested changes
I added few comments that I would like to see in this PR before merging to master. In a follow up (separate PR) I would ask you to restructure tests and then factor out configs. Let's do it one by one for better readability.

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +func ReadingTuplesFromFile(fileName string) []Tuple {
Minor: Exported functions in go require comments. You get lint warning otherwise.
Check **Funcs** section in https://tip.golang.org/doc/comment

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +	defer file.Close()
Swap those two lines

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +		}
Do you simply silently ignore otherwise?

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +		log.Fatal(err)
This supports my comment above. If you terminate here, you don't close opened file handles.

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +	regExp, err = regexp.Compile(`^\d,\s?\d,\s?\d$`)
This is tricky comment now: compiling regexp is expensive. You are compiling always the same pattern every time the function `stringToInt` is called. In this case, you better compile it once and reuse it in this function. Consider compiling it in factory function or call-once function or even singleton. It's a good place for writing charming code.

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +	var mapping map[int]Tuple = make(map[int]Tuple)
minor: `mapping` is misleading variable name

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +	for _, segment := range list {
minor: `segment` is here simply a tuple, isn't? Why calling it segment?

2022-10-06 06:43 UTC, radwandeeb commented on main/go.mod
> +replace packages/sorting => ../sorting
This does not work on every evn where you checkout your code. For example based on some env variables you could get: `package packages/sorting is not in GOROOT`. See following comment on how to structure it.

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +	the column values and the tuples are bound with a map, with respect to the condition of non-unique keys */
If it's a comment on the function, put it on top of it not inside it. If it's a comment on the following lines, keep it (it's here not the case).

2022-10-06 06:43 UTC, radwandeeb commented on sorting/sorting.go
> +		if _, ok := mapping[segment[column]]; ok {
Few comments on the logic in this function:
1. Space complexity: it duplicates the entire input set to a secondary hash-map. It duplicates again one column to another array. It duplicates the entire input set to the final list. That's expensive.
2. Deep in the code, we see here a piece of code that restricts us from sorting non-unique columns. Considering that there's no good reason to do it, we should not. If there's good reason, that should be enforced by the API not by the sort function.
3. What you actually want here is a map from `value-in-sort-column -> index-of-tuple-in-input-list` right? This reduces the size and handle duplicates.

2022-10-06 06:43 UTC, radwandeeb commented on sorting/result1.txt
> +0, 2, 6
It's good practice to not check in result files **unless** you use them in a test-case to assert result correctness.

2022-10-06 06:43 UTC, radwandeeb commented on main/go.mod
> +require packages/sorting v0.0.0-00010101000000-000000000000
I don't understand why you created sorting as a separate module. See https://github.com/golang-standards/project-layout#go-directories all what you need is `cmd` and either `internal` or `pkg`
You sorting is simple a package you import in the same module, no need to create a separate module for it. It's not only creates a mess, rather it introduces a dependency mismatch.
Good practice to have one module per repository. But again we don't need here 2 modules.

2022-10-08 16:01 UTC, radwandeeb approved these changes
It looks much better now. You can merge this change to the main branch

2022-10-08 16:01 UTC, radwandeeb commented on main.go
> +	"github.com/Mannaa-Baddour/Sorting-Tuples-in-Go/sorting"
Correct. That's the right way of doing it. The value of `module` in go.mod is the common prefix which tells go to use it from local storage not to pull it from Github.

2022-10-08 21:28 UTC, Mannaa-Baddour commented
Alright will do.
Sorry it took me a while I was sorting things up, and I've just finished watching a couple of videos on testing.
I'm gonna start working on the testing branch now.

2022-10-08 21:28 UTC, merged